### ISSUE TITLE
Crash after first run on OSX 10.6.2 

### ISSUE THREAD

**Issue by ghost** [qbranchcode/Qanban#29]
After the initial run of the server and creation of one account. A bit of task manipulation, the server was stopped (^C) and then later on tried to restart it with the following result.

java -Xmx512 -jar qanban-0.1.war 
2010-01-14 17:14:50.514::INFO:  Logging to STDERR via org.mortbay.log.StdErrLog
2010-01-14 17:14:50.697::INFO:  jetty-6.1.x
2010-01-14 17:14:51.100::INFO:  Extract file:/x/qanban-0.1.war to /var/folders/vy/vyT5mxRYE3qTrJIbRGlewE++CyE/-Tmp-/Jetty_0_0_0_0_8080_qanban.0.1.war____.kjee78/webapp
2010-01-14 17:14:57.183::INFO:  NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2010-01-14 17:15:01.563:/:INFO:  Initializing Spring root WebApplicationContext
2010-01-14 17:15:08.454::WARN:  Failed startup of context org.mortbay.jetty.webapp.WebAppContext@72cc5002{/,file:/x/qanban-0.1.war}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [org.codehaus.groovy.grails.plugins.scaffolding.ScaffoldingGrailsPlugin]!
    at java.security.AccessController.doPrivileged(Native Method)
    at se.qbranch.standalone.Starter.main(Unknown Source)
Caused by: org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [org.codehaus.groovy.grails.plugins.scaffolding.ScaffoldingGrailsPlugin]!
    ... 2 more
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2882)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:390)
    at java.lang.StringBuilder.append(StringBuilder.java:119)
    at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:232)
    at java.net.URL.<init>(URL.java:596)
    at java.net.URL.<init>(URL.java:464)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:192)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
    at java.beans.Introspector.instantiate(Introspector.java:1453)
    at java.beans.Introspector.findExplicitBeanInfo(Introspector.java:425)
    at java.beans.Introspector.<init>(Introspector.java:374)
    at java.beans.Introspector.getBeanInfo(Introspector.java:168)
    at java.security.AccessController.doPrivileged(Native Method)
2010-01-14 17:15:08.458::WARN:  Nested in org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [org.codehaus.groovy.grails.plugins.scaffolding.ScaffoldingGrailsPlugin]!:
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2882)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:390)
    at java.lang.StringBuilder.append(StringBuilder.java:119)
    at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:232)
    at java.net.URL.<init>(URL.java:596)
    at java.net.URL.<init>(URL.java:464)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:192)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
    at java.beans.Introspector.instantiate(Introspector.java:1453)
    at java.beans.Introspector.findExplicitBeanInfo(Introspector.java:425)
    at java.beans.Introspector.<init>(Introspector.java:374)
    at java.beans.Introspector.getBeanInfo(Introspector.java:168)
    at java.security.AccessController.doPrivileged(Native Method)
2010-01-14 17:15:08.536::INFO:  Started SocketConnector@0.0.0.0:8080

**Comment by xlson** [comment]
I'm guessing the culprit is a missing m (megabyte) which means your JVM has way to little memory.

You used: java -Xmx512 -jar qanban-0.1.war
It should be: java -Xmx512m -jar qanban-0.1.war

Try that instead, it should hopefully work. Keep me updated.

Kind regards,
/Leo

**Comment by ghost** [comment]
You are right Leo, 

My mistake, the server is now running as a stand alone server. Could not get it to start as a Tomcat service :-(

**Comment by xlson** [comment]
Are you the same guy that wrote on our blog?

I'm going away on vacation for a week but when I get back I'll be happy to help you. I'm guessing the easiest solution would be to have a way to specify where to store the database files.

In the meantime: the problem with the database and tomcat as a service could probably be sorted by changing the workdir for the command that starts tomcat (java ...Catalina) into a folder where the user (that runs tomcat) has write rights.

Another solution would be to download and build qanban from source. The latest version allows you to specify an external database using JNDI (MySQL for example).

**Comment by ghost** [comment]
yep I am sorry for spamming :-}

I'll give it a try building the latest checkin - have not builded Java code in some years now.

Have a great vacation.

**Comment by xlson** [comment]
No problem, the feedback is much appreciated. How did it go, have you built Qanban from source? 

Thanks, had a great time. I'm working through the backlog of emails and such now and will get back to you after that. If you could send me your email adress using gh mail we can continue the discussion over mail.

**Comment by xlson** [comment]
Closing this issue. Problem was a faulty run-param.
